<?php
// Database connection
$host = 'localhost';
$db = 'token_system';
$user = 'root';
$pass = '';
$conn = new mysqli($host, $user, $pass, $db);

if ($conn->connect_error) {
    die('Database connection failed: ' . $conn->connect_error);
}

// Fetch token data if form is submitted
$token_number = '';
$token = null;

if ($_SERVER['REQUEST_METHOD'] == 'POST') {
    $token_number = $_POST['token_number'];
    $sql = "SELECT token_number, name, bform, date, time FROM tokens WHERE token_number = ?";
    $stmt = $conn->prepare($sql);
    $stmt->bind_param('s', $token_number);
    $stmt->execute();
    $result = $stmt->get_result();

    if ($result->num_rows > 0) {
        $token = $result->fetch_assoc();
    }
    $stmt->close();
}

$conn->close();
?>
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Token Slip</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            margin: 0;
            padding: 0;
            background-color: #f9f9f9;
        }

        .container {
            max-width: 600px;
            margin: 50px auto;
            padding: 20px;
            background-color: #fff;
            border-radius: 8px;
            box-shadow: 0 4px 10px rgba(0, 0, 0, 0.1);
        }

        h2 {
            text-align: center;
            color: #4CAF50;
            margin-bottom: 20px;
        }

        form {
            margin-bottom: 20px;
            text-align: center;
        }

        input[type="text"] {
            width: 80%;
            padding: 10px;
            border: 1px solid #ddd;
            border-radius: 4px;
            font-size: 14px;
        }

        button {
            padding: 10px 20px;
            background-color: #4CAF50;
            color: white;
            border: none;
            border-radius: 4px;
            font-size: 14px;
            cursor: pointer;
        }

        button:hover {
            background-color: #45a049;
        }

        .token-slip {
            width: 100%;
            max-width: 400px;
            margin: 0 auto;
            padding: 20px;
            border: 1px solid #000;
            border-radius: 8px;
            background: #fff;
            font-size: 14px;
            line-height: 1.6;
            text-align: center;
        }

        .token-slip h3 {
            color: #000;
            font-size: 20px;
            margin-bottom: 10px;
            border-bottom: 1px dashed #000;
            padding-bottom: 5px;
        }

        .token-slip .info {
            margin: 10px 0;
            text-align: left;
        }

        .token-slip .info strong {
            display: inline-block;
            width: 120px;
        }

        .token-slip .footer {
            margin-top: 20px;
            font-size: 12px;
            color: #666;
            border-top: 1px dashed #000;
            padding-top: 10px;
        }

        .btn-print {
            display: block;
            width: 100%;
            margin-top: 20px;
            background-color: #4CAF50;
            color: white;
            border: none;
            padding: 10px;
            border-radius: 4px;
            cursor: pointer;
        }

        .btn-print:hover {
            background-color: #45a049;
        }
    </style>
</head>
<body>
    <div class="container">
        <img src="logo.webp" alt="DIF Logo" style="display: block; margin: 0 auto;" height="100px">
        <h2>Token Slip Generator</h2>
        <form method="POST">
            <input type="text" name="token_number" placeholder="Enter Token Number" required>
            <button type="submit">Fetch Data</button>
        </form>

        <?php if ($token): ?>
            <div class="token-slip" id="token-slip">
                <h3>Token Slip</h3>
                <div class="info"><strong>Token Number:</strong> <?php echo htmlspecialchars($token['token_number']); ?></div>
                <div class="info"><strong>Name:</strong> <?php echo htmlspecialchars($token['name']); ?></div>
                <div class="info"><strong>B-Form:</strong> <?php echo htmlspecialchars($token['bform']); ?></div>
                <div class="info"><strong>Date:</strong> <?php echo htmlspecialchars($token['date']); ?></div>
                <div class="info"><strong>Time:</strong> <?php echo htmlspecialchars($token['time']); ?></div>
                <div class="footer">Generated By: DIF IT System - For Admission Interview Use Only</div>
            </div>
            <button class="btn-print" onclick="printSlip()">Print Token Slip</button>
        <?php elseif ($_SERVER['REQUEST_METHOD'] == 'POST'): ?>
            <p style="color: red; text-align: center;">No token found for the given number.</p>
        <?php endif; ?>
    </div>

    <script>
        function printSlip() {
            const slipContent = document.getElementById('token-slip').outerHTML;
            const printWindow = window.open('', '_blank');
            printWindow.document.write(`
                <html>
                <head>
                    <title>Print Token Slip</title>
                    <style>
                        body {
                            font-family: Arial, sans-serif;
                            margin: 0;
                            padding: 0;
                            text-align: center;
                        }
                        .token-slip {
                            width: 100%;
                            max-width: 400px;
                            margin: 20px auto;
                            padding: 20px;
                            border: 1px solid #000;
                            border-radius: 8px;
                            background: #fff;
                            font-size: 14px;
                            line-height: 1.6;
                            text-align: center;
                        }
                        .token-slip h3 {
                            border-bottom: 1px dashed #000;
                        }
                        .footer {
                            font-size: 12px;
                            color: #666;
                        }
                    </style>
                </head>
                <body>${slipContent}</body>
                </html>
            `);
            printWindow.document.close();
            printWindow.focus();
            printWindow.print();
            printWindow.close();
        }
    </script>
</body>
</html>

